In [67]:
import numpy as np 
import pandas as pd

In [4]:
pwd

'/Users/yuqingdai/Documents/research_agent'

In [68]:
df = pd.read_parquet('./data/processed/dataset.parquet')

In [69]:
df

,date,ticker,open,high,low,close,adj_close,volume,ret_1d,ret_5d,...,ret_60d,ma_gap_10,ma_gap_20,ma_gap_60,vol_5d,vol_20d,rel_volume_20,range_5d,spy_ret_5d,target_fwd_5d
0,2018-03-29,A,66.750000,67.580002,66.110001,66.900002,62.864990,2711300.0,0.007530,-0.008448,...,-0.010355,-0.016928,-0.027517,-0.046162,0.021916,0.014515,1.170715,0.025562,-0.001972,-0.048580
1,2018-03-29,AAPL,41.952499,42.937500,41.724998,41.945000,39.416016,153594000.0,0.007809,-0.006337,...,-0.026007,-0.018251,-0.038350,-0.025612,0.030109,0.016752,1.154971,0.035110,-0.001972,0.003576
2,2018-03-29,ABBV,94.519997,95.540001,93.500000,94.650002,67.172668,7399400.0,0.004031,-0.035168,...,-0.038208,-0.074427,-0.135936,-0.139876,0.022916,0.032366,0.917402,0.048651,-0.001972,-0.051453
3,2018-03-29,ABT,59.570000,60.380001,59.299999,59.919998,52.047527,6656600.0,0.011649,-0.016576,...,0.019221,-0.020018,-0.026625,-0.005953,0.021235,0.014864,1.013874,0.024842,-0.001972,-0.039219
4,2018-03-29,ACGL,28.666668,28.766666,28.276667,28.530001,27.129135,3273000.0,-0.002448,0.014580,...,-0.030691,0.006799,-0.005438,-0.030365,0.010645,0.013925,1.121165,0.021687,-0.001972,-0.002103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989132,2026-03-26,XYZ,59.334999,61.400002,59.110001,59.369999,59.369999,5610300.0,-0.010665,0.006442,...,-0.099363,-0.003976,-0.043761,-0.028447,0.019404,0.045801,0.558470,0.037875,-0.022295,0.006906
989133,2026-03-26,YUM,158.860001,159.649994,156.100006,156.139999,156.139999,2034000.0,-0.018975,-0.000704,...,0.025415,-0.018543,-0.022347,-0.013879,0.012051,0.014314,1.113834,0.018895,-0.022295,-0.000320
989134,2026-03-26,ZBH,87.419998,89.610001,87.160004,89.150002,88.908569,1582600.0,0.017230,-0.007680,...,-0.015244,-0.005821,-0.034771,-0.029346,0.017933,0.016628,0.750110,0.023592,-0.022295,0.019518
989135,2026-03-26,ZBRA,205.270004,211.639999,203.710007,204.419998,204.419998,415000.0,-0.019333,-0.008584,...,-0.168145,-0.007333,-0.039666,-0.136579,0.013425,0.020995,0.542757,0.037263,-0.022295,-0.007729
989136,2026-03-26,ZTS,115.639999,118.580002,115.300003,116.629997,116.629997,2725900.0,-0.000685,0.005518,...,-0.074218,-0.002276,-0.029163,-0.060390,0.004964,0.017503,0.620926,0.026661,-0.022295,0.011232

In [10]:
df.columns

Index(['date', 'ticker', 'open', 'high', 'low', 'close', 'adj_close', 'volume',
       'ret_1d', 'ret_5d', 'ret_10d', 'ret_20d', 'ret_60d', 'ma_gap_10',
       'ma_gap_20', 'ma_gap_60', 'vol_5d', 'vol_20d', 'rel_volume_20',
       'range_5d', 'spy_ret_5d', 'target_fwd_5d'],
      dtype='object')

In [59]:
dg = df.loc[df.ticker == 'AAPL', ['date','close', 'adj_close', 'ret_5d']]
dg.head(10)

          date      close  adj_close    ret_5d
0   2018-03-29  41.945000  39.416031 -0.006337
82  2018-04-02  41.669998  39.157612  0.010549
164 2018-04-03  42.097500  39.559341 -0.025352
246 2018-04-04  42.902500  40.315800  0.019425
328 2018-04-05  43.200001  40.595352  0.037963
410 2018-04-06  42.095001  39.556999  0.003576
492 2018-04-09  42.512501  39.949318  0.020218
574 2018-04-10  43.312500  40.701077  0.028862
656 2018-04-11  43.110001  40.510788  0.004837
738 2018-04-12  43.535000  40.910172  0.007755

In [58]:
dg['adj_close'].shift(5).head(10)

0            NaN
82           NaN
164          NaN
246          NaN
328          NaN
410    39.416031
492    39.157612
574    39.559341
656    40.315800
738    40.595352
Name: adj_close, dtype: float64

In [62]:
(dg['adj_close'] / dg['adj_close'].shift(5) - 1).dropna()

410       0.003576
492       0.020218
574       0.028861
656       0.004837
738       0.007755
            ...
177237   -0.008516
177329   -0.005261
177421   -0.010188
177513    0.010723
177605    0.015786
Name: adj_close, Length: 2004, dtype: float64

In [ ]:
39.949318 / 39.416031- 1

0.003576412855977429

In [66]:
(df.adj_close / df.sort_values(['ticker', 'date']).groupby('ticker')['adj_close'].shift(5) - 1).dropna()

410       0.003576
411       0.011709
412      -0.030945
413       0.001939
414       0.001354
            ...
177692   -0.009409
177693   -0.020268
177694   -0.040561
177695   -0.020118
177696   -0.089447
Name: adj_close, Length: 177237, dtype: float64